title: vandermeer
email: ask@van.dermeer.de
description: >- # this means to ignore newlines until "baseurl:"
  Passionate implementer of ideas preferably for mobile and web with TypeScript, JavaScript, ReactNative and React
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://van.dermeer.de"

twitter:
  username: t_scharke
  card: summary

markdown: kramdown
theme: minima

exclude:
  - vdm-home.iml
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _saas
  style: compressed

header:
  keywords:
    - Freelancer
    - Software Artist
    - Freelancing Full Stack JavaScript Developer
    - TypeScript
    - JavaScript
    - ReactNative
    - React
    - Remote
    - Trainer
    - Redux
    - Mobile
    - Web
