title: vandermeer
email: ask@van.dermeer.de
description: >- # this means to ignore newlines until "baseurl:"
  Passionate implementer of ideas preferably for mobile and web with TypeScript, JavaScript, ReactNative and React
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://van.dermeer.de'

twitter:
  username: t_scharke
  card: summary

markdown: kramdown
theme: minima

exclude:
  - vdm-home.iml
  - Gemfile
  - Gemfile.lock
  - CNAME
  - package.json
  - node_modules
  - src
  - feed.xml
  - tsconfig.json
  - webpack.config.js
  - yarn.lock

sass:
  sass_dir: _saas
  style: compressed

header:
  keywords:
    - Freelancer
    - Software Artist
    - Full Stack
    - Developer
    - TypeScript
    - JavaScript
    - React Native
    - React
    - Remote
    - Trainer
    - Mobile
    - App
    - Web
    - SPA
    - API
    - Rest
    - GraphQL

  lesehelden:
    keywords:
      - Lesehelden
