title: vandermeer - Software Artists (Freelancer, React, TypeScript)
email: ask@van.dermeer.de
description: >- # this means to ignore newlines until "baseurl:"
  Passionate implementer of ideas preferably for mobile and web with TypeScript, JavaScript, ReactNative and React
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://van.dermeer.de'

twitter:
  username: t_scharke
  card: summary

markdown: kramdown
theme: minima

exclude:
  - vdm-home.iml
  - Gemfile
  - Gemfile.lock
  - CNAME
  - package.json
  - node_modules
  - src
  - feed.xml
  - tsconfig.json
  - webpack.config.js
  - yarn.lock

sass:
  sass_dir: _saas
  style: compressed

header:
  keywords:
    - Freelancer
    - Software Artist
    - Full Stack
    - Full-Stack
    - Developer
    - TypeScript
    - JavaScript
    - React
    - React Native
    - CSS
    - SCSS
    - Tailwind
    - TailwindCSS
    - Trainer
    - Mentor
    - Guide
    - Digital Nomad
    - Backend
    - Frontend
    - Mobile
    - App
    - Web
    - SPA
    - API
    - Rest
    - GraphQL
    - JSON
    - JSON-RPC
    - SOAP

  lesehelden:
    keywords:
      - Lesehelden
